title: Yefan Gao's Homepage
page-top-title: Yefan Gao
top-section-bg-text: Be what you wanna be
home-subtitle: Yefan Gao&ensp;|&ensp;高叶繁
copyright-text: '&copy; Yefan Gao 2023-2025. All Rights Reserved.'
